version: '3.6'

services:
    ledeuromedia:
        build: .
        container_name: ledeuromedia
        command: ['yarn', 'dev']
        ports:
            - '3000:3000'
        env_file: .env
        volumes:
            - ./:/app
